x3: configs: permissions: Add missing permissions for Launcher3
java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.android.launcher3 (/system_ext/priv-app/Launcher3QuickStep): android.permission.PACKAGE_USAGE_STATS}

* Also its makes bootloop

Signed-off-by: akmacc <arumugamguna7058@gmail.com>